post http://localhost:1233/drafts/create_problem
Content-Type: application/json

{
    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiYjhiMjJlZjctMDk5OS00NzJiLWFhOGEtN2ZkYzVmMmI1OWRmIiwiaWF0IjoxNjAwOTM2Nzc3fQ._ndQW0cE0vn1j3cZtaZhdWWOF8XTdMsob5zh8zCiwdk",
    "problem_name": "Test problem",
    "problem_slug": "testproblem",
    "problem_type": "standard",
    "problem_description": {
        "p": "This is a test and this will not work because it's not valid editorjs exported json. The parser will not generate html from this."
    },
    "problem_cl": 1.00,
    "problem_ml": 500,
    "testcases": "UEsDBAoDAAAAAO9xOVFrnrNQJQAAACUAAAAMAAAASGlkZGVuLTEudHh0SW5wdXQ6CjEyMzQ1Njc4OSAxCk91dHB1dDoKMTIzNDU2NzkwClBLAwQKAwAAAADZcTlR42tdWxsAAAAbAAAADAAAAFNhbXBsZS0xLnR4dElucHV0OgoxMjMgNDU2Ck91dHB1dDoKNTc5ClBLAQI/AwoDAAAAAO9xOVFrnrNQJQAAACUAAAAMACQAAAAAAAAAIIC0gQAAAABIaWRkZW4tMS50eHQKACAAAAAAAAEAGAAA/S8IFJPWAQD9LwgUk9YBAP0vCBST1gFQSwECPwMKAwAAAADZcTlR42tdWxsAAAAbAAAADAAkAAAAAAAAACCAtIFPAAAAU2FtcGxlLTEudHh0CgAgAAAAAAABABgAgOK/7xOT1gGA4r/vE5PWAYDiv+8Tk9YBUEsFBgAAAAACAAIAvAAAAJQAAAAAAA=="
}