post http://localhost:1233/drafts/getUserDrafts
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiYjhiMjJlZjctMDk5OS00NzJiLWFhOGEtN2ZkYzVmMmI1OWRmIiwiaWF0IjoxNjAxMDEzNjAzfQ.v3FeYR6sgPF_WiiWWjSErCAh0rrMJKeSW6aceeHMPsk"
}