post http://localhost:1233/auth/password_reset/sendPrEmail
Content-Type: application/json

{
    "email": "mdgaziurrahmannoor@gmail.com"
}

###

post http://localhost:1233/auth/password_reset/isValidToken
Content-Type: application/json

{
    "resetToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiYjhiMjJlZjctMDk5OS00NzJiLWFhOGEtN2ZkYzVmMmI1OWRmIiwiaWF0IjoxNjAwNzY4NDQ5fQ.8q8ZkxJIZOE4U81npSHYbPkBcLDhdJwDZFohBtBS2pM"
}

###

post http://localhost:1233/auth/password_reset/setPassword
Content-Type: application/json

{
    "resetToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiYjhiMjJlZjctMDk5OS00NzJiLWFhOGEtN2ZkYzVmMmI1OWRmIiwiaWF0IjoxNjAwNzY4NDQ5fQ.8q8ZkxJIZOE4U81npSHYbPkBcLDhdJwDZFohBtBS2pM",
    "newPassword" : "aaaa...."
}