post http://localhost:1233/userSettings
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiYjhiMjJlZjctMDk5OS00NzJiLWFhOGEtN2ZkYzVmMmI1OWRmIiwiaWF0IjoxNjAwOTM2Nzc3fQ._ndQW0cE0vn1j3cZtaZhdWWOF8XTdMsob5zh8zCiwdk",
  "email": "mdgaziurrahmannoor@gmail.com",
  "name": "Simp",
  "company": "Unify LLC",
  "institute": "Border Guard Public School and College, Sylhet",
  "website": "https://github.com/mdgaziur"
}