export const verdicts = {
  JUDGE_IN_QUEUE: 300,
  JUDGE_COMPILING: 301,
  JUDGE_TESTING: 302,
  JUDGE_CPU_LIMIT_EXCEEDED: 303,
  JUDGE_MEMORY_LIMIT_EXCEEDED: 304,
  JUDGE_RUNTIME_ERROR: 305,
  JUDGE_COMPILE_ERROR: 306,
  JUDGE_WRONG_ANSWER: 307,
  JUDGE_ACCEPTED: 308,
};
