export const errorCodes = {
    INVALID_ZIP: 101,
    TESTCASEFILE_MISMATCH: 102,
    INVALID_TESTCASE_FILE: 103,
    INVALID_FILE_TYPE: 104,
    FILE_NOT_ALLOWED: 105,
    DUPLICATE_FILE_NAMES: 106,
    EMPTY_ZIP: 107,
    USER_NOT_ALLOWED: 108,
    PROBLEM_DOES_NOT_EXISTS: 109
}