const cb_errorcodes = {
    ALREADY_LOGGED_IN: 1,
    FAILED_LOG_IN: 2,
    SESSION_EXPIRED: 3,
    WRONG_PASSWORD: 4,
    AUTH_ERROR: 5,
    NON_EXISTING_USER: 6,
    INCOMPLETE_FORM_REQEUST: 7,
    NOT_UNIQUE_DETAILS: 8,
    INVALID_TOKEN: 9,
    INVALID_FILE_TYPE: 10,
    FILE_SIZE_EXCEEDED: 11,
    NO_SAMPLE_OR_HIDDEN_TESTCASE: 12,
    INVALID_JSON_FORMAT: 13,
    NON_EXISTING_PROBLEM: 14,
    NOT_ALLOWED: 15
}

module.exports = cb_errorcodes;